#!/usr/bin/env bun
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Copies the PWA app source (src/ and static/) into the desktop/ workspace
 * so that Tauri can build from it with its own svelte.config.js and vite.config.js.
 *
 * Server-only files (+server.ts, hooks.server.ts) are stripped since Tauri
 * uses adapter-static (SPA mode) with no server.
 */

import { cpSync, existsSync, mkdirSync, rmSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';

const ROOT = join(import.meta.dirname, '..');
const DESKTOP = join(ROOT, 'desktop');
const SRC_FROM = join(ROOT, 'src');
const SRC_TO = join(DESKTOP, 'src');
const STATIC_FROM = join(ROOT, 'static');
const STATIC_TO = join(DESKTOP, 'static');

// Files/patterns to skip when copying src/
const SKIP_PATTERNS = ['+server.ts', '+server.js', 'hooks.server.ts', 'hooks.server.js'];

function shouldSkip(filename: string): boolean {
	return SKIP_PATTERNS.some((p) => filename.endsWith(p));
}

function copyFiltered(from: string, to: string) {
	if (!existsSync(from)) return;

	const entries = readdirSync(from);
	mkdirSync(to, { recursive: true });

	for (const entry of entries) {
		const srcPath = join(from, entry);
		const destPath = join(to, entry);
		const stat = statSync(srcPath);

		if (stat.isDirectory()) {
			// Skip api/ routes directory (server-only)
			if (entry === 'api' && from.includes('routes')) continue;
			copyFiltered(srcPath, destPath);
		} else {
			if (shouldSkip(entry)) {
				console.log(`  [skip] ${relative(ROOT, srcPath)}`);
				continue;
			}
			cpSync(srcPath, destPath);
		}
	}
}

console.log('Preparing Tauri build...');

// Clean previous copies
if (existsSync(SRC_TO)) {
	rmSync(SRC_TO, { recursive: true });
}
if (existsSync(STATIC_TO)) {
	rmSync(STATIC_TO, { recursive: true });
}

// Copy src/ with filtering
console.log(`Copying src/ → desktop/src/ (filtering server-only files)...`);
copyFiltered(SRC_FROM, SRC_TO);

// Copy static/ as-is
console.log(`Copying static/ → desktop/static/...`);
cpSync(STATIC_FROM, STATIC_TO, { recursive: true });

// Create +layout.ts with ssr = false for Tauri SPA mode
import { writeFileSync } from 'fs';
const layoutTs = join(SRC_TO, 'routes', '+layout.ts');
writeFileSync(
	layoutTs,
	`// Auto-generated by prepare-tauri.ts — Tauri requires SSR disabled\nexport const ssr = false;\n`
);
console.log('  [created] desktop/src/routes/+layout.ts (ssr = false)');

console.log('Tauri build preparation complete.');
